export const registrationContent = {
  id: {
    eyebrow: 'Registrasi Peserta',
    title: 'Registrasi Visitor',
    subtitle:
      'Daftarkan diri Anda untuk menghadiri ProBuild INTIM 2026 dan pilih talkshow yang diminati.',
    eventInfo: 'Informasi Event',
    eventDate: 'Tanggal',
    eventVenue: 'Lokasi',
    important: 'Informasi Penting',
    notes: [
      'Satu nomor WhatsApp hanya dapat digunakan satu kali untuk event ini.',
      'Anda dapat memilih lebih dari satu talkshow.',
      'Ketersediaan talkshow ditentukan oleh kapasitas saat registrasi diproses.',
      'Perubahan pilihan talkshow dilakukan melalui panitia.',
    ],
    formTitle: 'Data Peserta',
    formSubtitle: 'Kolom bertanda * wajib diisi.',
    fullName: 'Nama lengkap',
    whatsapp: 'Nomor WhatsApp',
    whatsappHint: 'Contoh: 0812 3456 7890',
    email: 'Alamat email',
    organization: 'Organisasi / perusahaan',
    jobTitle: 'Jabatan',
    city: 'Kota',
    address: 'Alamat',
    optional: 'Opsional',
    talkshowsTitle: 'Pilih Talkshow',
    talkshowsSubtitle: 'Pilih satu atau beberapa sesi yang ingin Anda ikuti.',
    unlimited: 'Kapasitas tersedia',
    remaining: 'Sisa {count} kursi',
    waitlist: 'Daftar tunggu',
    full: 'Penuh',
    closed: 'Pendaftaran ditutup',
    submit: 'Selesaikan Registrasi',
    submitting: 'Memproses Registrasi...',
    loadError: 'Informasi registrasi belum dapat dimuat.',
    retry: 'Coba Lagi',
    generalError: 'Registrasi belum berhasil. Periksa data Anda dan coba kembali.',
    consent:
      'Dengan mendaftar, Anda menyetujui penggunaan data ini untuk keperluan registrasi, komunikasi, dan operasional event ProBuild INTIM 2026.',
  },
  en: {
    eyebrow: 'Participant Registration',
    title: 'Visitor Registration',
    subtitle:
      'Register to attend ProBuild INTIM 2026 and select the talkshows you are interested in.',
    eventInfo: 'Event Information',
    eventDate: 'Date',
    eventVenue: 'Venue',
    important: 'Important Information',
    notes: [
      'A WhatsApp number can only be used once for this event.',
      'You may select more than one talkshow.',
      'Talkshow availability depends on capacity when registration is processed.',
      'Talkshow changes are handled by the event committee.',
    ],
    formTitle: 'Participant Details',
    formSubtitle: 'Fields marked * are required.',
    fullName: 'Full name',
    whatsapp: 'WhatsApp number',
    whatsappHint: 'Example: +62 812 3456 7890',
    email: 'Email address',
    organization: 'Organization / company',
    jobTitle: 'Job title',
    city: 'City',
    address: 'Address',
    optional: 'Optional',
    talkshowsTitle: 'Select Talkshows',
    talkshowsSubtitle: 'Choose one or more sessions you would like to attend.',
    unlimited: 'Capacity available',
    remaining: '{count} seats remaining',
    waitlist: 'Waitlist',
    full: 'Full',
    closed: 'Registration closed',
    submit: 'Complete Registration',
    submitting: 'Processing Registration...',
    loadError: 'Registration information could not be loaded.',
    retry: 'Try Again',
    generalError: 'Registration was not completed. Check your details and try again.',
    consent:
      'By registering, you consent to the use of this data for registration, communication, and event operations for ProBuild INTIM 2026.',
  },
};

export const eTicketContent = {
  id: {
    successEyebrow: 'Registrasi Berhasil',
    successTitle: 'Registrasi Berhasil!',
    successSubtitle: 'Terima kasih, {name}. Registrasi dan e-ticket Anda telah berhasil dibuat.',
    ticketEyebrow: 'E-Ticket Peserta',
    ticketTitle: 'E-Ticket ProBuild INTIM 2026',
    ticketSubtitle: 'Tunjukkan QR Code ini kepada panitia saat tiba di lokasi event.',
    ticketLabel: 'E-Ticket Peserta',
    registrationNumber: 'Nomor Registrasi',
    participant: 'Peserta',
    currentStatus: 'Status Saat Ini',
    eventDate: 'Tanggal Event',
    location: 'Lokasi',
    presentQr: 'Tunjukkan QR Code Saat Check-in',
    qrInstruction: 'Satu QR Code berlaku untuk seluruh hari event. Jangan membagikannya.',
    qrAlt: 'QR Code e-ticket peserta',
    selectedTalkshows: 'Pilihan Talkshow',
    confirmed: 'Terkonfirmasi',
    waitlisted: 'Daftar Tunggu',
    waitlistPosition: 'Posisi daftar tunggu: {position}',
    noTalkshows: 'Tidak ada talkshow terkonfirmasi atau dalam daftar tunggu.',
    dailyAttendance: 'Status Kehadiran Harian',
    statuses: {
      not_checked_in: 'NOT CHECKED IN',
      partially_checked_in: 'PARTIALLY CHECKED IN',
      checked_in: 'CHECKED IN',
    },
    databaseNote:
      'Status ini dibaca langsung dari database. PDF menampilkan status pada saat dokumen diunduh.',
    downloadPdf: 'Download E-Ticket PDF',
    backHome: 'Kembali ke Beranda',
    loading: 'Memuat e-ticket...',
    errorTitle: 'E-Ticket Tidak Ditemukan',
    unavailableTitle: 'E-Ticket Belum Dapat Ditampilkan',
    errorMessage: 'E-ticket belum dapat dimuat. Periksa kembali tautan Anda.',
    retry: 'Coba Lagi',
    backToRegistration: 'Kembali ke registrasi',
  },
  en: {
    successEyebrow: 'Registration Successful',
    successTitle: 'Registration Successful!',
    successSubtitle: 'Thank you, {name}. Your registration and e-ticket are ready.',
    ticketEyebrow: 'Participant E-Ticket',
    ticketTitle: 'ProBuild INTIM 2026 E-Ticket',
    ticketSubtitle: 'Present this QR Code to the event committee when you arrive.',
    ticketLabel: 'Participant E-Ticket',
    registrationNumber: 'Registration Number',
    participant: 'Participant',
    currentStatus: 'Current Status',
    eventDate: 'Event Date',
    location: 'Location',
    presentQr: 'Present QR Code at Check-in',
    qrInstruction: 'One QR Code applies to every event day. Do not share it.',
    qrAlt: 'Participant e-ticket QR Code',
    selectedTalkshows: 'Selected Talkshows',
    confirmed: 'Confirmed',
    waitlisted: 'Waitlisted',
    waitlistPosition: 'Waitlist position: {position}',
    noTalkshows: 'No confirmed or waitlisted talkshows.',
    dailyAttendance: 'Daily Attendance Status',
    statuses: {
      not_checked_in: 'NOT CHECKED IN',
      partially_checked_in: 'PARTIALLY CHECKED IN',
      checked_in: 'CHECKED IN',
    },
    databaseNote:
      'This status is read directly from the database. The PDF shows the status when downloaded.',
    downloadPdf: 'Download E-Ticket PDF',
    backHome: 'Back to Home',
    loading: 'Loading e-ticket...',
    errorTitle: 'E-Ticket Not Found',
    unavailableTitle: 'E-Ticket Is Temporarily Unavailable',
    errorMessage: 'The e-ticket could not be loaded. Check the link and try again.',
    retry: 'Try Again',
    backToRegistration: 'Back to registration',
  },
};
